### ISSUE TITLE
Repository add-on repository.aussieaddons-devel uses plain HTTP for add-on downloads

### ISSUE THREAD

**Issue by shtrom** [aussieaddons/repo-devel#4]
Kodi complains that `
WARNING: Repository add-on repository.aussieaddons-devel uses plain HTTP for add-on downloads in path http://aussieaddons.com/repository-devel/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!`

I think the complaint is justified. I would rather only download executable modules without MitM risks.

Is this something that can be easily enabled? Let's Encrypt should make that reasonably straightforwards.

The issue is also present for the non `-devel` version of the repo.

**Comment by glennguy** [comment]
Better late than never - this is sorted now. Thanks @shtrom!
